### PR TITLE
add properties for making an image button

### PR DESCRIPTION
**Pull request by zachkrall**
addresses issue #2 

adds the following to Clickable:
- properties
    - image: default null
    - tint: default null
    - noTint: default true
    - filter: default null
- methods
    - drawImage: called inside of draw if an image is defined. applies all image related p5 functions

example:
Screen Shot 2020-08-27 at 1 35 25 PM
Screen Shot 2020-08-27 at 1 35 30 PM
```javascript
  click3 = new Clickable();
  click3.image = clickImg;
  click3.locate(250,250);
  click3.resize(100,100);
  click3.text = "";

  click3.onOutside = function () {
    this.color = "#FFFFFF";
    this.noTint = true;
  }

  click3.onHover = function () {
    this.color = "#AA33AA";
    this.noTint = false;
    this.tint = "#FF0000";
  }
```

### CODE REVIEW

**Comment by Samathingamajig** [comment]
@zachkrall Please fix line 13 in `library/p5.clickable.js` and re-add `var` to the `for (i = 0; ...) {` because that would cause the issue that needed #15 again

**Comment by zachkrall** [comment]
@Samathingamajig oops, thanks! I copied everything between example and library folder to ensure they matched and I didn't notice that.

**Comment by Samathingamajig** [comment]
👍

**Comment by Samathingamajig** [comment]
Did you start your fork with the most recent version of the project? Because #13 was also unfixed and still needs to be refixed (i saw that you fixed 1/2 of the typos that had been fixed)

**Comment by zachkrall** [comment]
@Samathingamajig yeah, I forked it from master like an hour ago at this commit https://github.com/zachkrall/p5.clickable/commit/4005c6eb26f345e996a112fd5da78132d7685112

the readme mentions something about other features that were overwritten too. if there's a better commit I should rebase from I can do that.

**Comment by Samathingamajig** [comment]
maybe you were editing in the example directory and i dont think the library in the example directory was ever updated with those?

**Comment by zachkrall** [comment]
yeah that's what happened. I made an assumption that those two files were synced before hand. I think I've fixed that now.

**Comment by Samathingamajig** [comment]
*tbh i didnt know that the example didnt just reference the library a few folders up, something like `../../library/p5.clickable.js` and was actually just a duplicate file*

**Comment by zachkrall** [comment]
yeah the static p5.js file in the repo is also another file to manually update overtime. I wonder if there's value in creating an examples folder that uses rollup so that p5.clickable and p5.js can be referenced from their sources.

**Comment by Samathingamajig** [comment]
the p5.js should just use the CDN, and since the example can just use github pages it should just use the `../../` idk

**Comment by zachkrall** [comment]
@Lartu what are your thoughts on changing the structure of the examples folder?

**Comment by Lartu** [comment]
Be my guest if you want to change the structure of the examples folder as long as it's clear and easy to understand for new users of the library (sorry for the late reply but I spent most of 2020 off github!)

**Comment by zachkrall** [comment]
@Lartu no worries! I just updated this PR so there shouldn't be any merge conflicts for adding the image button properties and maybe the changes to the examples folder would be better as a separate PR.

**Comment by Lartu** [comment]
Amazing! Thank you!

**Comment by Lartu** [comment]
Merged, thank you very much for your contribution!

**Pull request merged**
